// Made ChatGPT write this data, it includes data of 50 words with hints.

const words = [
    { word: "apple", hint: "Common fruit." },
    { word: "banana", hint: "Yellow fruit." },
    { word: "computer", hint: "Electronic device." },
    { word: "ocean", hint: "Large body of water." },
    { word: "mountain", hint: "High landform." },
    { word: "guitar", hint: "Musical instrument." },
    { word: "library", hint: "Book storage." },
    { word: "pizza", hint: "Italian dish." },
    { word: "sunshine", hint: "Direct light." },
    { word: "umbrella", hint: "Rain protection." },
    { word: "bicycle", hint: "Two-wheeled vehicle." },
    { word: "camera", hint: "Photo device." },
    { word: "dolphin", hint: "Marine mammal." },
    { word: "elephant", hint: "Large animal." },
    { word: "fireworks", hint: "Explosive display." },
    { word: "garden", hint: "Plant area." },
    { word: "hamburger", hint: "Fast food." },
    { word: "island", hint: "Land surrounded by water." },
    { word: "jigsaw", hint: "Puzzle pieces." },
    { word: "kangaroo", hint: "Australian marsupial." },
    { word: "lemonade", hint: "Citrus drink." },
    { word: "moonlight", hint: "Nighttime light." },
    { word: "notebook", hint: "Writing pad." },
    { word: "orchestra", hint: "Musical ensemble." },
    { word: "penguin", hint: "Antarctic bird." },
    { word: "queen", hint: "Female ruler." },
    { word: "rainbow", hint: "Color spectrum." },
    { word: "sunglasses", hint: "Eye protection." },
    { word: "telephone", hint: "Communication device." },
    { word: "umbrella", hint: "Rain shield." },
    { word: "violin", hint: "Stringed instrument." },
    { word: "watermelon", hint: "Fruit with seeds." },
    { word: "xylophone", hint: "Percussion instrument." },
    { word: "yacht", hint: "Boat for leisure." },
    { word: "zebra", hint: "Striped animal." },
    { word: "robot", hint: "Automated machine." },
    { word: "cloud", hint: "Sky formation." },
    { word: "butterfly", hint: "Flying insect." },
    { word: "globe", hint: "World model." },
    { word: "whale", hint: "Ocean mammal." },
    { word: "skateboard", hint: "Rolling board." },
    { word: "volcano", hint: "Erupting mountain." },
    { word: "snorkel", hint: "Underwater tube." },
    { word: "pizza", hint: "Italian dish." },
    { word: "piano", hint: "Musical keyboard." },
    { word: "kite", hint: "Flying toy." },
    { word: "helicopter", hint: "Rotorcraft." },
    { word: "giraffe", hint: "Tall mammal." },
    { word: "fireplace", hint: "Indoor fire." },
    { word: "fishing", hint: "Catch activity." },
    { word: "ballet", hint: "Dance style." },
    { word: "cactus", hint: "Desert plant." },
  ];
  